apiVersion: v1
kind: Service
metadata:
  name: autodeploy77
  namespace: namespace-workflow-1716464089883
spec:
  type: LoadBalancer
  selector:
    app: autodeploy77
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000